### ISSUE TITLE
.xlsx file not created 

### ISSUE THREAD

**Issue by Celies** [Lemeard/Skript#2]
If set an output-folder that you havn't created yet, you get the following error: 

[ERROR] workbook_close(): Error creating 'C:\Utskrift\Karlskrona_2023M08.xlsx'. System error = No such file or directory
Error: Error in libxlsxwriter: 'Error creating output xlsx file. Usually a permissions error.'

Creating the folder beforehand solves the problem. Might be needed in the instructions.

**Comment by Lemeard** [comment]
Bra kommentar! Skriptet kollar nu om utskriftsmappen man angett existerar. Gör den inte det så skapas mappen.
